export const DATA = {
  hero: {
    name: "Vishal Mahajan",
    location: "Mumbai",
    Timezone: "GMT+5:30",
    avatarSrc: "/VishalRMahajan.webp",
    social: {
      GitHub: "https://github.com/VishalRMahajan",
      LinkedIn: "https://linkedin.com/in/VishalRMahajan",
      X: "https://twitter.com/VishalRMahajan",
      Email: "mailto:me@vishalrmahajan.in",
      LeetCode: "https://leetcode.com/VishalRMahajan/",
      Resume: "https://resume.vishalrmahajan.in?src=portfolio",
    },
  },
  footer: {
    name: "Vishal Rajesh Mahajan",
    websiteUrl: "https://vishalrmahajan.in",
    VideoCredit: `Video by <a href="https://pixabay.com/users/u_zys3fy54t3-36732626/?utm_source=link-attribution&utm_medium=referral&utm_campaign=video&utm_content=164386">u_zys3fy54t3</a> from <a href="https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=video&utm_content=164386">Pixabay</a>`,
  },
  skills: [
    "python",
    "javascript",
    "typescript",
    "cpp",
    "nodejs",
    "express",
    "fastapi",
    "flask",
    "react",
    "tailwindcss",
    "postgres",
    "mysql",
    "mongo",
    "redis",
    "linux",
    "git",
    "postman",
    "sklearn",
  ],
  work: [
    {
      company: "The Good Game Theory",
      href: "https://www.thegoodgametheory.com/",
      Skills: ["NodeJs", "Express"],
      location: "Remote",
      title: "Backend Developer Intern",
      logoUrl: "/work-logo/tggt.webp",
      start: "May 2025",
      end: "Present",
      description: "Joined Just Now, Will update soon.",
    },
  ],
  projects: [
    {
      description: "AI-Powered Accident Detection System",
      title: "Nirikshan",
      videosrc: "",
      githubLink: "https://github.com/VishalRMahajan/Nirikshan",
      deployed: false,
      deployedlink: "",
      content: [
        "An AI-powered real-time accident detection system that leverages a custom-trained YOLO11m model, achieving 99% mAP@50, 89.3% mAP@50–95, 96.8% precision, and 96.4% recall across 9 accident categories. It processes CCTV feeds frame-by-frame using a FastAPI WebSocket server and streams annotated video for immediate incident awareness.",
        "The system includes a full-stack incident monitoring dashboard with a 3-stage workflow (Verify → Ongoing → Resolved), secure Google OAuth authentication, PostgreSQL database integration, and a sleek, responsive UI built using shadcn/ui components for effective, user-friendly incident management.",
      ],
    },
    {
      description: "Just run npx vishalrmahajan and see it in action",
      title: "NPX VishalRMahajan",
      videosrc: "https://youtu.be/aqoyMsZe2K0",
      githubLink: "https://github.com/VishalRMahajan/npx-vishalrmahajan",
      deployed: false,
      deployedlink: "",
      content: [
        "NPX VishalRMahajan is a CLI-based interactive portfolio that runs entirely inside your terminal, launched with a single npx command. It showcases projects, experience, and contact info in a colorful, keyboard-navigable interface",
        "Built using Node.js and libraries like chalk, cfonts, and terminal-kit, the portfolio offers real-time navigation and custom commands, delivering a seamless and engaging developer showcase directly in the command line. ",
      ],
    },
    {
      description: "MERN-Based Food Ordering Platform",
      title: "Nivala",
      videosrc: "https://youtu.be/3Axl_S_9uqA",
      githubLink: "https://github.com/VishalRMahajan/Nivala",
      deployed: true,
      deployedlink: "https://nivala.vishalrmahajan.in",
      content: [
        "Nivala is a MERN stack-based food ordering web app featuring a 3-tier microservices architecture (Frontend, Admin, Backend), with secure JWT authentication, role-based access control (RBAC), and a responsive, mobile-first UI.",
        "The backend is built for robustness and scalability, integrating bcrypt password hashing, Mongoose ODM, persistent cart handling, promo code validation, and CORS-enabled RESTful APIs for secure and efficient data management.",
      ],
    },
  ],
  blogs: [
    {
      title: "A Developer CLI Portfolio That Lives Inside Your Terminal",
      url: "https://medium.com/@vishal_mahajan/a-developer-cli-portfolio-that-lives-inside-your-terminal-npx-vishalrmahajan-12b5518c9976",
      description:
        "How I built a portfolio that runs entirely in the terminal using npx. Features, design, and the tech stack behind it.",
      publishedAt: "2025-07-20",
      platform: "Medium",
    },
  ],
} as const;
